[package]
name = "zylith"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.1"

[dev-dependencies]
cairo_test = "2.15.1"
snforge_std = "0.55.0"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
panic-backtrace = true

[[target.starknet-contract]]
sierra = true
casm = true
